# version: '3.8'

services:
  myportfolio2:
    image:  myportfolio2
    container_name:  myportfolio2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
