server.port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  data:
    mongodb:
      uri: mongodb+srv://doadmin:26X5vR91G08Dkut3@db-mongodb-nyc3-48171-8b2c1b6a.mongo.ondigitalocean.com/admin?retryWrites=true&w=majority
      authentication-database: admin
      auto-index-creation: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

okta:
  oauth2:
    issuer: https://dev-mwu16egco04uokhe.us.auth0.com
    audience: https://dev-mwu16egco04uokhe.us.auth0.com/api/v2/

auth0:
  domain: dev-mwu16egco04uokhe.us.auth0.com
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: https://dev-mwu16egco04uokhe.us.auth0.com/api/v2/
---
  spring:
    config:
      activate:
        on-profile: docker

    data:
    mongodb:
      host: mongodb
      port: 27017
      database: myportfolio2
      username: root
      password: password
      authentication-database: admin

